package com.slf.sms.bo;

import com.slf.common.base.BaseObj;


public class LsDxhk extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.DXHKID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private Long dxhkid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.TDBH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String tdbh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.DXID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String dxid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.PCH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String pch;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.ZT
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String zt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.CLJG
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String cljg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.YYSLSH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String yyslsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.FSBZ
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String fsbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.DLFLSH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String dlflsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.FSHM
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private String fshm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHK.DLID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    private Long dlid;
    
    private String dxhkids;
    
    private String fhsj;
    
    private String fhms;
    
	public String getFhms() {
		return fhms;
	}

	public void setFhms(String fhms) {
		this.fhms = fhms;
	}

	public String getFhsj() {
		return fhsj;
	}

	public void setFhsj(String fhsj) {
		this.fhsj = fhsj;
	}

	public String getDxhkids() {
		return dxhkids;
	}

	public void setDxhkids(String dxhkids) {
		this.dxhkids = dxhkids;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.DXHKID
     *
     * @return the value of LS_DXHK.DXHKID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public Long getDxhkid() {
        return dxhkid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.DXHKID
     *
     * @param dxhkid the value for LS_DXHK.DXHKID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setDxhkid(Long dxhkid) {
        this.dxhkid = dxhkid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.TDBH
     *
     * @return the value of LS_DXHK.TDBH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getTdbh() {
        return tdbh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.TDBH
     *
     * @param tdbh the value for LS_DXHK.TDBH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setTdbh(String tdbh) {
        this.tdbh = tdbh == null ? null : tdbh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.DXID
     *
     * @return the value of LS_DXHK.DXID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getDxid() {
        return dxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.DXID
     *
     * @param dxid the value for LS_DXHK.DXID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setDxid(String dxid) {
        this.dxid = dxid == null ? null : dxid.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.PCH
     *
     * @return the value of LS_DXHK.PCH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getPch() {
        return pch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.PCH
     *
     * @param pch the value for LS_DXHK.PCH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setPch(String pch) {
        this.pch = pch == null ? null : pch.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.ZT
     *
     * @return the value of LS_DXHK.ZT
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.ZT
     *
     * @param zt the value for LS_DXHK.ZT
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.CLJG
     *
     * @return the value of LS_DXHK.CLJG
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getCljg() {
        return cljg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.CLJG
     *
     * @param cljg the value for LS_DXHK.CLJG
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setCljg(String cljg) {
        this.cljg = cljg == null ? null : cljg.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.YYSLSH
     *
     * @return the value of LS_DXHK.YYSLSH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getYyslsh() {
        return yyslsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.YYSLSH
     *
     * @param yyslsh the value for LS_DXHK.YYSLSH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setYyslsh(String yyslsh) {
        this.yyslsh = yyslsh == null ? null : yyslsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.FSBZ
     *
     * @return the value of LS_DXHK.FSBZ
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getFsbz() {
        return fsbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.FSBZ
     *
     * @param fsbz the value for LS_DXHK.FSBZ
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setFsbz(String fsbz) {
        this.fsbz = fsbz == null ? null : fsbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.DLFLSH
     *
     * @return the value of LS_DXHK.DLFLSH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getDlflsh() {
        return dlflsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.DLFLSH
     *
     * @param dlflsh the value for LS_DXHK.DLFLSH
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setDlflsh(String dlflsh) {
        this.dlflsh = dlflsh == null ? null : dlflsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.FSHM
     *
     * @return the value of LS_DXHK.FSHM
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public String getFshm() {
        return fshm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.FSHM
     *
     * @param fshm the value for LS_DXHK.FSHM
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setFshm(String fshm) {
        this.fshm = fshm == null ? null : fshm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHK.DLID
     *
     * @return the value of LS_DXHK.DLID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHK.DLID
     *
     * @param dlid the value for LS_DXHK.DLID
     *
     * @ibatorgenerated Wed May 08 16:11:29 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }
}