package com.slf.sms.bo;

import com.slf.common.base.BaseObj;


public class LsQydx extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.QYDXID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Long qydxid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.DLFLSH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String dlflsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.PCH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Integer pch;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.YYS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String yys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.FSHM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String fshm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.ZT
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String zt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.FSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String fssj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.FSCS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Integer fscs;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.URL
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String url;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.CLBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String clbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_QYDX.CLJG
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String cljg;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.QYDXID
     *
     * @return the value of LS_QYDX.QYDXID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Long getQydxid() {
        return qydxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.QYDXID
     *
     * @param qydxid the value for LS_QYDX.QYDXID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setQydxid(Long qydxid) {
        this.qydxid = qydxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.DLID
     *
     * @return the value of LS_QYDX.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.DLID
     *
     * @param dlid the value for LS_QYDX.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.DLFLSH
     *
     * @return the value of LS_QYDX.DLFLSH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getDlflsh() {
        return dlflsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.DLFLSH
     *
     * @param dlflsh the value for LS_QYDX.DLFLSH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDlflsh(String dlflsh) {
        this.dlflsh = dlflsh == null ? null : dlflsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.PCH
     *
     * @return the value of LS_QYDX.PCH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Integer getPch() {
        return pch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.PCH
     *
     * @param pch the value for LS_QYDX.PCH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setPch(Integer pch) {
        this.pch = pch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.YYS
     *
     * @return the value of LS_QYDX.YYS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getYys() {
        return yys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.YYS
     *
     * @param yys the value for LS_QYDX.YYS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setYys(String yys) {
        this.yys = yys == null ? null : yys.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.FSHM
     *
     * @return the value of LS_QYDX.FSHM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getFshm() {
        return fshm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.FSHM
     *
     * @param fshm the value for LS_QYDX.FSHM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setFshm(String fshm) {
        this.fshm = fshm == null ? null : fshm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.ZT
     *
     * @return the value of LS_QYDX.ZT
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.ZT
     *
     * @param zt the value for LS_QYDX.ZT
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.FSSJ
     *
     * @return the value of LS_QYDX.FSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getFssj() {
        return fssj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.FSSJ
     *
     * @param fssj the value for LS_QYDX.FSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setFssj(String fssj) {
        this.fssj = fssj == null ? null : fssj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.FSCS
     *
     * @return the value of LS_QYDX.FSCS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Integer getFscs() {
        return fscs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.FSCS
     *
     * @param fscs the value for LS_QYDX.FSCS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setFscs(Integer fscs) {
        this.fscs = fscs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.URL
     *
     * @return the value of LS_QYDX.URL
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.URL
     *
     * @param url the value for LS_QYDX.URL
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.CLBZ
     *
     * @return the value of LS_QYDX.CLBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getClbz() {
        return clbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.CLBZ
     *
     * @param clbz the value for LS_QYDX.CLBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setClbz(String clbz) {
        this.clbz = clbz == null ? null : clbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_QYDX.CLJG
     *
     * @return the value of LS_QYDX.CLJG
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getCljg() {
        return cljg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_QYDX.CLJG
     *
     * @param cljg the value for LS_QYDX.CLJG
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setCljg(String cljg) {
        this.cljg = cljg == null ? null : cljg.trim();
    }
}