package com.slf.sms.bo;

import com.slf.common.base.BaseObj;



public class XtKzcs extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.CSID
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private Long csid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.KZLB
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private String kzlb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.KZMC
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private String kzmc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.KZZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private String kzz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.MRZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private String mrz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.BZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private String bz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.XGBZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private String xgbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.SZRQ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private String szrq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.SZSJ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private String szsj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XT_KZCS.SZRID
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    private Long szrid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.CSID
     *
     * @return the value of XT_KZCS.CSID
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public Long getCsid() {
        return csid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.CSID
     *
     * @param csid the value for XT_KZCS.CSID
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setCsid(Long csid) {
        this.csid = csid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.KZLB
     *
     * @return the value of XT_KZCS.KZLB
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public String getKzlb() {
        return kzlb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.KZLB
     *
     * @param kzlb the value for XT_KZCS.KZLB
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setKzlb(String kzlb) {
        this.kzlb = kzlb == null ? null : kzlb.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.KZMC
     *
     * @return the value of XT_KZCS.KZMC
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public String getKzmc() {
        return kzmc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.KZMC
     *
     * @param kzmc the value for XT_KZCS.KZMC
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setKzmc(String kzmc) {
        this.kzmc = kzmc == null ? null : kzmc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.KZZ
     *
     * @return the value of XT_KZCS.KZZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public String getKzz() {
        return kzz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.KZZ
     *
     * @param kzz the value for XT_KZCS.KZZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setKzz(String kzz) {
        this.kzz = kzz == null ? null : kzz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.MRZ
     *
     * @return the value of XT_KZCS.MRZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public String getMrz() {
        return mrz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.MRZ
     *
     * @param mrz the value for XT_KZCS.MRZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setMrz(String mrz) {
        this.mrz = mrz == null ? null : mrz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.BZ
     *
     * @return the value of XT_KZCS.BZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.BZ
     *
     * @param bz the value for XT_KZCS.BZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.XGBZ
     *
     * @return the value of XT_KZCS.XGBZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public String getXgbz() {
        return xgbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.XGBZ
     *
     * @param xgbz the value for XT_KZCS.XGBZ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setXgbz(String xgbz) {
        this.xgbz = xgbz == null ? null : xgbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.SZRQ
     *
     * @return the value of XT_KZCS.SZRQ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public String getSzrq() {
        return szrq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.SZRQ
     *
     * @param szrq the value for XT_KZCS.SZRQ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setSzrq(String szrq) {
        this.szrq = szrq == null ? null : szrq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.SZSJ
     *
     * @return the value of XT_KZCS.SZSJ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public String getSzsj() {
        return szsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.SZSJ
     *
     * @param szsj the value for XT_KZCS.SZSJ
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setSzsj(String szsj) {
        this.szsj = szsj == null ? null : szsj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XT_KZCS.SZRID
     *
     * @return the value of XT_KZCS.SZRID
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public Long getSzrid() {
        return szrid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XT_KZCS.SZRID
     *
     * @param szrid the value for XT_KZCS.SZRID
     *
     * @ibatorgenerated Thu Feb 28 10:23:26 CST 2013
     */
    public void setSzrid(Long szrid) {
        this.szrid = szrid;
    }
}