package com.slf.sms.bo;

import java.math.BigDecimal;

import com.slf.common.base.BaseObj;

public class XxDlqb extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DLQB.DLQBID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private Long dlqbid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DLQB.DLID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DLQB.ZJYE
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private BigDecimal zjye;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DLQB.YFYE
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private BigDecimal yfye;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DLQB.DLQBID
     *
     * @return the value of XX_DLQB.DLQBID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public Long getDlqbid() {
        return dlqbid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DLQB.DLQBID
     *
     * @param dlqbid the value for XX_DLQB.DLQBID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setDlqbid(Long dlqbid) {
        this.dlqbid = dlqbid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DLQB.DLID
     *
     * @return the value of XX_DLQB.DLID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DLQB.DLID
     *
     * @param dlid the value for XX_DLQB.DLID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DLQB.ZJYE
     *
     * @return the value of XX_DLQB.ZJYE
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public BigDecimal getZjye() {
        return zjye;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DLQB.ZJYE
     *
     * @param zjye the value for XX_DLQB.ZJYE
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setZjye(BigDecimal zjye) {
        this.zjye = zjye;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DLQB.YFYE
     *
     * @return the value of XX_DLQB.YFYE
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public BigDecimal getYfye() {
        return yfye;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DLQB.YFYE
     *
     * @param yfye the value for XX_DLQB.YFYE
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setYfye(BigDecimal yfye) {
        this.yfye = yfye;
    }
}