package com.slf.sms.bo;

import com.slf.common.base.BaseObj;


public class XxDxgjz extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DXGJZ.GJZID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private Long gjzid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DXGJZ.TDBH
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private String tdbh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DXGJZ.GJZLB
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private String gjzlb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DXGJZ.DLID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DXGJZ.GJZ
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private String gjz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_DXGJZ.ZT
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    private String zt;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DXGJZ.GJZID
     *
     * @return the value of XX_DXGJZ.GJZID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public Long getGjzid() {
        return gjzid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DXGJZ.GJZID
     *
     * @param gjzid the value for XX_DXGJZ.GJZID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setGjzid(Long gjzid) {
        this.gjzid = gjzid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DXGJZ.TDBH
     *
     * @return the value of XX_DXGJZ.TDBH
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public String getTdbh() {
        return tdbh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DXGJZ.TDBH
     *
     * @param tdbh the value for XX_DXGJZ.TDBH
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setTdbh(String tdbh) {
        this.tdbh = tdbh == null ? null : tdbh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DXGJZ.GJZLB
     *
     * @return the value of XX_DXGJZ.GJZLB
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public String getGjzlb() {
        return gjzlb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DXGJZ.GJZLB
     *
     * @param gjzlb the value for XX_DXGJZ.GJZLB
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setGjzlb(String gjzlb) {
        this.gjzlb = gjzlb == null ? null : gjzlb.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DXGJZ.DLID
     *
     * @return the value of XX_DXGJZ.DLID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DXGJZ.DLID
     *
     * @param dlid the value for XX_DXGJZ.DLID
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DXGJZ.GJZ
     *
     * @return the value of XX_DXGJZ.GJZ
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public String getGjz() {
        return gjz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DXGJZ.GJZ
     *
     * @param gjz the value for XX_DXGJZ.GJZ
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setGjz(String gjz) {
        this.gjz = gjz == null ? null : gjz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_DXGJZ.ZT
     *
     * @return the value of XX_DXGJZ.ZT
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_DXGJZ.ZT
     *
     * @param zt the value for XX_DXGJZ.ZT
     *
     * @ibatorgenerated Tue Feb 19 23:12:18 CST 2013
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }
}