package com.slf.sms.bo;

import com.slf.common.base.BaseObj;

public class XxJrhpp extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_JRHPP.JRHPPID
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    private Long jrhppid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_JRHPP.DLID
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_JRHPP.DXQM
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    private String dxqm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_JRHPP.DXJRH
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    private String dxjrh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_JRHPP.PPZT
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    private String ppzt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_JRHPP.CJSJ
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    private String cjsj;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_JRHPP.JRHPPID
     *
     * @return the value of XX_JRHPP.JRHPPID
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public Long getJrhppid() {
        return jrhppid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_JRHPP.JRHPPID
     *
     * @param jrhppid the value for XX_JRHPP.JRHPPID
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public void setJrhppid(Long jrhppid) {
        this.jrhppid = jrhppid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_JRHPP.DLID
     *
     * @return the value of XX_JRHPP.DLID
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_JRHPP.DLID
     *
     * @param dlid the value for XX_JRHPP.DLID
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_JRHPP.DXQM
     *
     * @return the value of XX_JRHPP.DXQM
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public String getDxqm() {
        return dxqm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_JRHPP.DXQM
     *
     * @param dxqm the value for XX_JRHPP.DXQM
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public void setDxqm(String dxqm) {
        this.dxqm = dxqm == null ? null : dxqm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_JRHPP.DXJRH
     *
     * @return the value of XX_JRHPP.DXJRH
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public String getDxjrh() {
        return dxjrh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_JRHPP.DXJRH
     *
     * @param dxjrh the value for XX_JRHPP.DXJRH
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public void setDxjrh(String dxjrh) {
        this.dxjrh = dxjrh == null ? null : dxjrh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_JRHPP.PPZT
     *
     * @return the value of XX_JRHPP.PPZT
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public String getPpzt() {
        return ppzt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_JRHPP.PPZT
     *
     * @param ppzt the value for XX_JRHPP.PPZT
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public void setPpzt(String ppzt) {
        this.ppzt = ppzt == null ? null : ppzt.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_JRHPP.CJSJ
     *
     * @return the value of XX_JRHPP.CJSJ
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public String getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_JRHPP.CJSJ
     *
     * @param cjsj the value for XX_JRHPP.CJSJ
     *
     * @ibatorgenerated Wed Apr 06 21:28:49 CST 2016
     */
    public void setCjsj(String cjsj) {
        this.cjsj = cjsj == null ? null : cjsj.trim();
    }
}