package com.slf.sms.bo;

import com.slf.common.base.BaseObj;


public class XxQy extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_QY.QYID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Long qyid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_QY.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_QY.QYMC
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String qymc;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_QY.DLM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String dlm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_QY.JYM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String jym;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_QY.HTURL
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String hturl;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_QY.ZT
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String zt;
    
    private int yxfsbz;
    
    private int kqbz; //一客一签开启标志 1开启 0不开启
    
    private int jrhppbz; //2016-04-05 sxw 接入号替换标志 0不替换 1替换

    
    public int getJrhppbz() {
		return jrhppbz;
	}

	public void setJrhppbz(int jrhppbz) {
		this.jrhppbz = jrhppbz;
	}

	public int getKqbz() {
		return kqbz;
	}

	public void setKqbz(int kqbz) {
		this.kqbz = kqbz;
	}

	public int getYxfsbz() {
		return yxfsbz;
	}

	public void setYxfsbz(int yxfsbz) {
		this.yxfsbz = yxfsbz;
	}

	private String gjzjyzt;
    
    private String hzbmdbz;
    
    public String getHzbmdbz() {
		return hzbmdbz;
	}

	public void setHzbmdbz(String hzbmdbz) {
		this.hzbmdbz = hzbmdbz;
	}

	private long pretime = 0;
    
    public long getPretime() {
		return pretime;
	}

	public void setPretime(long pretime) {
		this.pretime = pretime;
	}

	private int nrzs;

    public int getNrzs() {
		return nrzs;
	}

	public void setNrzs(int nrzs) {
		this.nrzs = nrzs;
	}

	public String getGjzjyzt() {
		return gjzjyzt;
	}

	public void setGjzjyzt(String gjzjyzt) {
		this.gjzjyzt = gjzjyzt;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_QY.QYID
     *
     * @return the value of XX_QY.QYID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Long getQyid() {
        return qyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_QY.QYID
     *
     * @param qyid the value for XX_QY.QYID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setQyid(Long qyid) {
        this.qyid = qyid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_QY.DLID
     *
     * @return the value of XX_QY.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_QY.DLID
     *
     * @param dlid the value for XX_QY.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_QY.QYMC
     *
     * @return the value of XX_QY.QYMC
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getQymc() {
        return qymc;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_QY.QYMC
     *
     * @param qymc the value for XX_QY.QYMC
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setQymc(String qymc) {
        this.qymc = qymc == null ? null : qymc.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_QY.DLM
     *
     * @return the value of XX_QY.DLM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getDlm() {
        return dlm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_QY.DLM
     *
     * @param dlm the value for XX_QY.DLM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDlm(String dlm) {
        this.dlm = dlm == null ? null : dlm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_QY.JYM
     *
     * @return the value of XX_QY.JYM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getJym() {
        return jym;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_QY.JYM
     *
     * @param jym the value for XX_QY.JYM
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setJym(String jym) {
        this.jym = jym == null ? null : jym.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_QY.HTURL
     *
     * @return the value of XX_QY.HTURL
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getHturl() {
        return hturl;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_QY.HTURL
     *
     * @param hturl the value for XX_QY.HTURL
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setHturl(String hturl) {
        this.hturl = hturl == null ? null : hturl.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_QY.ZT
     *
     * @return the value of XX_QY.ZT
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_QY.ZT
     *
     * @param zt the value for XX_QY.ZT
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }
}