package com.slf.sms.bo;

import com.slf.common.base.BaseObj;


public class XxYkyq extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_YKYQ.YKYQBID
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    private Long ykyqbid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_YKYQ.DLID
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_YKYQ.HM
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    private Integer hm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_YKYQ.QM
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    private String qm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_YKYQ.SCRQ
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    private String scrq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column XX_YKYQ.SCSJ
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    private String scsj;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_YKYQ.YKYQBID
     *
     * @return the value of XX_YKYQ.YKYQBID
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public Long getYkyqbid() {
        return ykyqbid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_YKYQ.YKYQBID
     *
     * @param ykyqbid the value for XX_YKYQ.YKYQBID
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public void setYkyqbid(Long ykyqbid) {
        this.ykyqbid = ykyqbid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_YKYQ.DLID
     *
     * @return the value of XX_YKYQ.DLID
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_YKYQ.DLID
     *
     * @param dlid the value for XX_YKYQ.DLID
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_YKYQ.HM
     *
     * @return the value of XX_YKYQ.HM
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public Integer getHm() {
        return hm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_YKYQ.HM
     *
     * @param hm the value for XX_YKYQ.HM
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public void setHm(Integer hm) {
        this.hm = hm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_YKYQ.QM
     *
     * @return the value of XX_YKYQ.QM
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public String getQm() {
        return qm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_YKYQ.QM
     *
     * @param qm the value for XX_YKYQ.QM
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public void setQm(String qm) {
        this.qm = qm == null ? null : qm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_YKYQ.SCRQ
     *
     * @return the value of XX_YKYQ.SCRQ
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public String getScrq() {
        return scrq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_YKYQ.SCRQ
     *
     * @param scrq the value for XX_YKYQ.SCRQ
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public void setScrq(String scrq) {
        this.scrq = scrq == null ? null : scrq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column XX_YKYQ.SCSJ
     *
     * @return the value of XX_YKYQ.SCSJ
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public String getScsj() {
        return scsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column XX_YKYQ.SCSJ
     *
     * @param scsj the value for XX_YKYQ.SCSJ
     *
     * @ibatorgenerated Sat Nov 01 13:04:57 CST 2014
     */
    public void setScsj(String scsj) {
        this.scsj = scsj == null ? null : scsj.trim();
    }
}